#include "test_libsha512_utils.h"

/**
 * @brief Fill a test message with deterministic bytes
 * @details The exact text is not important for this test. A stable byte pattern
 * makes every boundary case reproducible while still exercising ordinary binary
 * input rather than a special empty buffer
 *
 * @param message Descriptor that receives the generated bytes
 * @param message_size Number of bytes to generate
 * @return SUCCESS when the message descriptor is ready to hash
 */
static Return prepare_boundary_message(
	memory *message,
	size_t message_size)
{
	/* Status returned by this function through provide()
	   Default value assumes successful completion */
	Return status = SUCCESS;

	unsigned char *message_data = NULL;

	/* Require a real descriptor and a non-empty size before writing the pattern */
	ASSERT(message != NULL);
	ASSERT(message_size > 0U);
	ASSERT(SUCCESS == m_resize(message,message_size,ZERO_NEW_MEMORY));

	/* Ask libmem for writable bytes only after the descriptor has the requested
	   length */
	IF(message != NULL)
	{
		message_data = m_data(unsigned char,message);
	}

	ASSERT(message_data != NULL);

	/* Fill with a predictable alphabet pattern. It is simple to inspect, but it
	   still exercises binary hashing rather than relying on string helpers */
	for(size_t byte_index = 0U; SUCCESS == status && byte_index < message_size; byte_index++)
	{
		message_data[byte_index] = (unsigned char)('A' + (byte_index % 26U));
	}

	provide(status);
}

/**
 * @brief Prepare a two-piece chunk plan for one boundary message
 * @details The first chunk leaves one byte for the second update call. For a
 * 128-byte message this specifically exercises the path where buffered input
 * completes a full SHA-512 block
 *
 * @param chunks Descriptor that receives two size_t chunk lengths
 * @param message_size Total message size that the chunks must cover
 * @return SUCCESS when the chunk descriptor contains a complete plan
 */
static Return prepare_boundary_chunks(
	memory *chunks,
	size_t message_size)
{
	/* Status returned by this function through provide()
	   Default value assumes successful completion */
	Return status = SUCCESS;

	size_t *chunk_data = NULL;

	/* The boundary comparison needs exactly two chunks: almost the whole message
	   first, then one final byte */
	ASSERT(chunks != NULL);
	ASSERT(message_size > 0U);
	ASSERT(SUCCESS == m_resize(chunks,2U,ZERO_NEW_MEMORY));

	/* Retrieve writable chunk storage after libmem has allocated two entries */
	IF(chunks != NULL)
	{
		chunk_data = m_data(size_t,chunks);
	}

	ASSERT(chunk_data != NULL);

	/* The final one-byte update is the important part of this scenario because
	   it can complete a buffered SHA-512 block */
	IF(chunk_data != NULL)
	{
		chunk_data[0] = message_size - 1U;
		chunk_data[1] = 1U;
	}

	provide(status);
}

/**
 * @brief Compare one-shot and chunked hashing at one SHA-512 boundary
 * @details A size close to the 128-byte block or 112-byte padding threshold can
 * use different internal paths. The public digest must stay the same no matter
 * which path is used
 *
 * @param message_size Boundary size to exercise
 * @return SUCCESS when both hashing styles produce one digest
 */
static Return check_sha512_boundary_size(size_t message_size)
{
	/* Status returned by this function through provide()
	   Default value assumes successful completion */
	Return status = SUCCESS;

	/* Keep all temporary buffers in libmem descriptors so setup, hashing, and
	   cleanup follow the same rules as the rest of the test environment */
	m_create(unsigned char,message);
	m_create(size_t,chunks);
	m_create(unsigned char,one_shot_digest);
	m_create(unsigned char,chunked_digest);

	/* Build one deterministic boundary-sized message and a chunk plan that
	   finishes it with a one-byte update */
	ASSERT(SUCCESS == prepare_boundary_message(message,message_size));
	ASSERT(SUCCESS == prepare_boundary_chunks(chunks,message_size));

	/* Hash the exact same bytes through the one-shot and chunked paths. Boundary
	   behavior is correct only if both paths produce the same digest */
	ASSERT(SUCCESS == calculate_sha512_digest(
		m_data_ro(unsigned char,message),
		message->length,
		one_shot_digest));
	ASSERT(SUCCESS == calculate_sha512_digest_in_chunks(
		m_data_ro(unsigned char,message),
		message->length,
		chunks,
		chunked_digest));
	ASSERT(SUCCESS == assert_sha512_digest_matches(one_shot_digest,chunked_digest));

	/* Free descriptors with call() so a failed boundary check does not leak the
	   buffers allocated for that size */
	call(m_del(message));
	call(m_del(chunks));
	call(m_del(one_shot_digest));
	call(m_del(chunked_digest));

	provide(status);
}

/**
 * @brief Check SHA-512 behavior around block and padding boundaries
 * @details The selected sizes sit on both sides of important internal limits:
 * 112 bytes for final padding and 128 bytes for a full SHA-512 block
 *
 * @return SUCCESS when all boundary sizes produce stable digests
 */
Return test_libsha512_0004(void)
{
	INITTEST;

	/* These sizes sit just before, on, and just after SHA-512 padding and block
	   limits. That keeps the test small while touching the important edges */
	const size_t boundary_sizes[] = {111U,112U,113U,127U,128U,129U};

	/* Exercise each boundary independently so a failure points to the exact
	   message size that broke the one-shot versus chunked guarantee */
	for(size_t size_index = 0U; SUCCESS == status && size_index < sizeof(boundary_sizes) / sizeof(boundary_sizes[0]); size_index++)
	{
		run(check_sha512_boundary_size(boundary_sizes[size_index]));
	}

	RETURN_STATUS;
}
