title: Precizer
description: precizer is a CLI application for verifying file integrity after synchronization. The program recursively traverses directories, creates a database of files with their checksums, and performs comparisons.
show_downloads: true
theme: jekyll-theme-cayman
