ARG BUILD=production
FROM ubuntu:24.04@sha256:d1e2e92c075e5ca139d51a140fff46f84315c0fdce203eab2807c7e495eff4f9 AS ubuntu

ARG BUILD
ENV BUILD=${BUILD}

RUN set -eux; \
    apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      gcc make \
      llvm llvm-dev \
      libpcre2-dev \
      libsqlite3-dev \
      libcmocka0 libcmocka-dev \
      upx-ucl; \
    rm -rf /var/lib/apt/lists/*;

WORKDIR /precizer

COPY . /precizer
RUN useradd -m builder && chown -R builder:builder /precizer

USER builder
RUN make ${BUILD}

CMD ["sh", "-c", "make tests"]
