ARG BUILD=production
FROM alpine:edge AS alpine

ARG BUILD
ENV BUILD=${BUILD}

RUN set -eux; \
     apk add --no-cache build-base llvm pcre2-dev pcre2-static fts-dev argp-standalone sqlite-dev upx

WORKDIR /precizer

COPY . /precizer
RUN adduser -D builder && chown -R builder:builder /precizer

USER builder
RUN make ${BUILD}

CMD ["sh", "-c", "make tests-debug"]
