FROM archlinux@sha256:237637c52069930ed7fc76c76f04b6b6b9cf82c5222ae002b7932df983cb69c1 AS arch

RUN set -eux; \
     pacman -Syu --noconfirm --needed base-devel gcc-libs clang sqlite llvm pcre2 upx inetutils; \
     pacman -Scc --noconfirm

WORKDIR /precizer

COPY . /precizer
RUN useradd -m builder && chown -R builder:builder /precizer

USER builder
ARG BUILD=production
ARG COMPILER=
ENV COMPILER=${COMPILER}
ENV TEST_TYPE=tests
RUN make -j ${BUILD}

CMD ["sh", "-c", "make -j ${TEST_TYPE}"]
