ARG BUILD=production
FROM alpine:3.20 AS alpine

ARG BUILD
ENV BUILD=${BUILD}

RUN set -eux; \
     apk add --no-cache build-base llvm pcre2-dev fts-dev argp-standalone upx

WORKDIR /precizer

COPY . /precizer
RUN adduser -D builder && chown -R builder:builder /precizer

USER builder
RUN make ${BUILD}

CMD ["sh", "-c", "make tests-debug"]
