FROM rockylinux/rockylinux:10@sha256:827d37bc128288ccf160ee318bb3cb92d591164cb217e92f8bc61e3982ae1834 AS rocky

RUN set -eux; \
	dnf -y update; \
	dnf -y install dnf-plugins-core; \
	dnf config-manager --set-enabled crb; \
	dnf -y install \
		which \
		gcc \
		clang \
		make \
		llvm \
		llvm-devel \
		libasan libubsan \
		sqlite sqlite-devel \
		glibc-devel glibc-static \
		pcre2 pcre2-devel pcre2-static \
		zip; \
	dnf -y clean all; \
	rm -rf /var/cache/dnf

# UPX is disabled because no package is available
# TODO: Install UPX and enable compression when a working package is available

WORKDIR /precizer

COPY . /precizer
RUN useradd -m builder && chown -R builder:builder /precizer

USER builder
ARG BUILD=production
ARG COMPILER=
ENV COMPILER=${COMPILER}
ENV TEST_TYPE=tests
RUN make -j ${BUILD} UPX=true

CMD ["sh", "-c", "make -j ${TEST_TYPE}"]
