ARG BUILD=production
FROM gentoo/stage3:latest AS gentoo

ARG BUILD
ENV BUILD=${BUILD}

# deps: gcc, make, llvm, pcre2 (static), upx, useradd
RUN (emerge-webrsync || emerge --sync); \
    emerge --ask=n --getbinpkg --usepkgonly \
      llvm-core/llvm \
      dev-build/cmake \
      app-arch/upx; \
    echo "dev-libs/libpcre2 static-libs" >> /etc/portage/package.use/libpcre2; \
    emerge --ask=n \
      dev-libs/libpcre2 \
      dev-util/cmocka; \
    emerge --depclean

WORKDIR /precizer

COPY . /precizer
RUN useradd -m builder && chown -R builder:builder /precizer

USER builder

RUN make -j ${BUILD}

CMD ["sh", "-c", "export PATH=\"$(ls -d /usr/lib/llvm/[0-9]*/bin 2>/dev/null):$PATH\"; echo $PATH; make -j tests"]
