FROM archlinux@sha256:681569955d1d17313ef7134acc8b5cd8adcda2fc24709bed472d95e1cf3d71a1 AS arch

RUN set -eux; \
     pacman -Syu --noconfirm --needed base-devel gcc-libs clang sqlite llvm pcre2 upx; \
     pacman -Scc --noconfirm

WORKDIR /precizer

COPY . /precizer
RUN useradd -m builder && chown -R builder:builder /precizer

USER builder
ARG BUILD=production
ARG COMPILER=
ENV COMPILER=${COMPILER}
ENV TEST_TYPE=tests
RUN make -j ${BUILD}

CMD ["sh", "-c", "make -j ${TEST_TYPE}"]
