ARG BUILD=production
FROM almalinux:10@sha256:3ea6bed76e47c1a816ed7e1ed7be8661efcf6984bec90bcad5ec73b66b6754ce AS almalinux

ARG BUILD
ENV BUILD=${BUILD}

RUN set -eux; \
    dnf -y update; \
    dnf -y install dnf-plugins-core; \
    dnf config-manager --set-enabled crb; \
    dnf -y install epel-release; \
    dnf -y install almalinux-release-devel; \
    dnf -y makecache; \
    dnf -y install \
      which \
      gcc-toolset-15-gcc \
      gcc-toolset-15-libubsan-devel \
      gcc-toolset-15-libasan-devel \
      gcc \
      make \
      llvm \
      llvm-devel \
      sqlite sqlite-devel \
      glibc-devel \
      pcre2 pcre2-devel \
      libcmocka libcmocka-devel \
      upx; \
    dnf -y --enablerepo=devel install pcre2-static glibc-static; \
    dnf -y clean all; \
    rm -rf /var/cache/dnf

WORKDIR /precizer

COPY . /precizer
RUN useradd -m builder && chown -R builder:builder /precizer

USER builder
RUN scl enable gcc-toolset-15 -- make ${BUILD}

CMD ["sh", "-c", "scl enable gcc-toolset-15 -- make tests"]
