FROM fedora:latest@sha256:6c75d5bf57cb0fa5aa4b92c6a83c86c791644496d9ac230de7711f5b8ec3b898 AS fedora

RUN set -eux; \
    dnf -y update; \
    dnf -y install \
      which \
      gcc \
      libasan \
      libubsan \
      clang \
      compiler-rt \
      lld \
      make \
      llvm \
      llvm-devel \
      sqlite sqlite-devel \
      glibc-devel glibc-static \
      pcre2 pcre2-devel pcre2-static \
      upx; \
    dnf -y clean all; \
    rm -rf /var/cache/dnf /var/cache/libdnf5

WORKDIR /precizer

COPY . /precizer
RUN useradd -m builder && chown -R builder:builder /precizer

USER builder
ARG BUILD=production
ARG COMPILER=
ARG MAKE_ARGS=
ENV COMPILER=${COMPILER}
ENV TEST_TYPE=tests
RUN make -j ${BUILD} ${MAKE_ARGS}

CMD ["sh", "-c", "make -j ${TEST_TYPE}"]
