FROM rockylinux:9@sha256:d7be1c094cc5845ee815d4632fe377514ee6ebcf8efaed6892889657e5ddaaa6 AS rocky

RUN set -eux; \
    dnf -y update; \
    dnf -y install dnf-plugins-core; \
    dnf config-manager --set-enabled crb; \
    dnf -y install epel-release; \
    dnf -y install gcc-toolset-15-gcc; \
    dnf -y install gcc-toolset-15-libubsan-devel; \
    dnf -y install gcc-toolset-15-libasan-devel; \
    dnf -y makecache; \
    dnf -y install \
    which \
    gcc \
    clang \
    make \
    llvm \
    sqlite sqlite-devel \
    glibc-devel \
    llvm-devel \
    pcre2 pcre2-devel \
    upx; \
    dnf -y --enablerepo=devel install pcre2-static glibc-static; \
    dnf -y clean all; \
    rm -rf /var/cache/dnf

WORKDIR /precizer

COPY . /precizer
RUN useradd -m builder && chown -R builder:builder /precizer

USER builder
ARG BUILD=production
ARG COMPILER=
ENV COMPILER=${COMPILER}
ENV TEST_TYPE=tests
RUN if [ -n "$COMPILER" ]; then make -j ${BUILD}; else scl enable gcc-toolset-15 -- make -j ${BUILD}; fi

CMD ["sh", "-c", "if [ -n \"$COMPILER\" ]; then make -j ${TEST_TYPE}; else scl enable gcc-toolset-15 -- make -j ${TEST_TYPE}; fi"]
