ARG BUILD=production
FROM debian:trixie-slim@sha256:1d3c811171a08a5adaa4a163fbafd96b61b87aa871bbc7aa15431ac275d3d430 AS debian

ARG BUILD
ENV BUILD=${BUILD}

RUN set -eux; \
      apt-get update; \
      DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      gcc \
      make \
      llvm \
      llvm-dev \
      libpcre2-dev \
      libsqlite3-dev \
      libcmocka0 libcmocka-dev \
      upx-ucl; \
    rm -rf /var/lib/apt/lists/*;

WORKDIR /precizer

COPY . /precizer
RUN useradd -m builder && chown -R builder:builder /precizer

USER builder
RUN make -j ${BUILD}

CMD ["sh", "-c", "make -j tests"]
