name: Complete build & test matrix across all platforms

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-matrix:
    name: Build and test on every OS
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run Docker matrix
        run: make docker-check-every-os
