name: FreeBSD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]
  merge_group:

permissions:
  contents: read

jobs:
  tests:
    name: tests
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build and test on FreeBSD 14.2
        uses: vmactions/freebsd-vm@4807432c7cab1c3f97688665332c0b932062d31f # v1.4.3
        with:
          release: "14.2"
          prepare: |
            pkg install -y gcc gmake llvm pcre2 sqlite3 cmocka upx
          run: |
            gmake -j portable
            gmake -j tests-debug
