name: Precizer

on:
  push:
    tags:
      - "*.*.*"

jobs:
  get_tag_info:
    name: Get annotated tag message
    runs-on: ubuntu-24.04

    outputs:
      version: ${{ steps.tag_message.outputs.version }}
      body: ${{ steps.tag_message.outputs.body }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get annotated tag message
        id: tag_message
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

          VERSION="${GITHUB_REF#refs/tags/}"

          {
            echo "version=$VERSION"
            echo 'body<<EOF'
            git tag -l --format='%(contents)' "$VERSION"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

  build_linux_x86_64:
    name: Build & release Linux x86_64
    runs-on: ubuntu-24.04
    needs: get_tag_info

    env:
      VERSION: ${{ needs.get_tag_info.outputs.version }}
      BODY: ${{ needs.get_tag_info.outputs.body }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make libpcre2-dev llvm upx gh

      - name: Build project (Linux x86_64)
        run: |
          make portable
          zip --junk-paths precizer_linux_x86_64_v${{ env.VERSION }}.zip precizer
          ZIP_COMMENT="Linux x86_64 static portable binary (single executable)"
          echo "$ZIP_COMMENT" | zip -z precizer_linux_x86_64_v${{ env.VERSION }}.zip

      - name: Run tests (Linux x86_64)
        run: make tests

      - name: Create GitHub Release with gh CLI
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            "precizer_linux_x86_64_v${{ env.VERSION }}.zip" \
            --title "v${{ github.ref_name }}" \
            --notes "${{ env.BODY }}" \
            --draft

  build_linux_arm64:
    name: Build & attach Linux arm64
    runs-on: ubuntu-24.04-arm
    needs: get_tag_info

    env:
      VERSION: ${{ needs.get_tag_info.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make libpcre2-dev llvm upx gh

      - name: Build project (Linux arm64)
        run: |
          make portable
          zip --junk-paths precizer_linux_arm64_v${{ env.VERSION }}.zip precizer
          ZIP_COMMENT="Linux arm64 static portable binary (single executable)"
          echo "$ZIP_COMMENT" | zip -z precizer_linux_arm64_v${{ env.VERSION }}.zip

      - name: Run tests (Linux arm64)
        run: make tests

      - name: Upload Linux arm64 asset
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            "precizer_linux_arm64_v${{ env.VERSION }}.zip" \
            --clobber

  build_macos_arm64:
    name: Build & attach macOS arm64
    runs-on: macos-latest
    needs: get_tag_info

    env:
      VERSION: ${{ needs.get_tag_info.outputs.version }}

    steps:
      - name: Checkout repository (exclude tests/examples/long)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /*
            !tests/examples/long/**

      - name: Install dependencies
        run: |
          brew update
          brew install llvm upx|| true

      - name: Build project (macOS arm64)
        run: |
          make dynamic-production
          ZIP_COMMENT="macOS arm64 dynamic loadable binary (single executable)"
          echo "$ZIP_COMMENT" | zip -z precizer_linux_arm64_v${{ env.VERSION }}.zip
          zip --junk-paths precizer_macos_arm64_v${{ env.VERSION }}.zip precizer

      - name: Run tests (macOS arm64)
        run: make tests

      - name: Upload macOS arm64 asset
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            "precizer_macos_arm64_v${{ env.VERSION }}.zip#macOS arm64 binary" \
            --clobber
