name: Precizer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential \
        libpcre2-dev \
        cmake \
        llvm

    - name: Build project
      run: make portable

    - name: Run tests
      run: |
        cd tests
        make sanitize run

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: precizer
